### ISSUE TITLE
【Rust】ランダムコドン表作成プログラム

### ISSUE THREAD

**Issue by citrus-mizuha** [citrus-mizuha/Codoner#6]

**Comment by Pik6C** [comment]
I added https://github.com/citrus-mizuha/Codoner/blob/main/Gene_codon/random-refer-memo/Rust_random_encoder/src/main.rs (commit [cffeaa1](https://github.com/citrus-mizuha/Codoner/commit/cffeaa12207f7a3077fff27bbc2f41cc4543e10b))
